### ISSUE TITLE
Set up smtp email settings

### ISSUE THREAD

**Issue by jasleenkaur83** [LogicalOutcomes/SIS-LimeSurvey#6] opened 2017-05-26 16:52 UTC
DUE: Late June (not urgent)
When we set up new users, only email addresses from logicaloutcomes.net and gmail.com receive the email confirmations with passwords. Other email addresses must be set up on the server and then the survey admin must send a separate message with the username and temporary password. This is not an urgent issue but should be fixed later in June

**Comment by jasleenkaur83** [comment] 2017-05-26 18:46
If we use inmotion email server, mails do not get delivered to Logicaloutcomes.net domain. However if we set notification recipient address other than LO (e.g @gmail.com, @outlook.com) notification emails get delivered successfully.

**Comment by gilliankerr** [comment] 2017-05-26 23:10
Jasleen, please send me the smtp settings (e.g., username, passwords, inmotion mail settings) on skype and i will pass them to Trevinder.

**Comment by gilliankerr** [comment] 2017-05-27 11:17
Trivender, jasleen does not have email settings. Please set up email using your own server temporarily and tell me what you need to set up with a LogicalOutcomes.net email address.

**Comment by trivender** [comment] 2017-05-29 10:57
After some googling I changed below settings in cpanel and emails started emails getting delivered to LogicalOutcomes domain from limesurvey.  But there is still a problem that emails are going to junk folder. I think we need to add some SPF records to sort this out. Now I flipped the setting back to what they were initially.

### New settings
![after](https://cloud.githubusercontent.com/assets/1558981/26547019/9391f62c-448a-11e7-95a4-6975fc7031bb.PNG)

### Old settings
![before](https://cloud.githubusercontent.com/assets/1558981/26547020/93bd6a0a-448a-11e7-91e6-e159c443db00.PNG)

### Emails going to junk.
![image](https://cloud.githubusercontent.com/assets/1558981/26547091/ebe083f2-448a-11e7-9632-ef3044421add.png)

Some places I asked for help:
https://forums.cpanel.net/threads/conflict-with-office365.602039/
https://webmasters.stackexchange.com/questions/106644/conflict-with-office365

Please note that it is not at all related to limeusurvey and more of email administration. I got some pointers in google search and I will try my best to sort this out. **As this is not my expertise so I can not commit ETA to resolve this problem**. If this is something very urgent then I guess you should reach out some expert webmaster.

**Further Plan:**
I also have o365 login account using my domain . I created that some time before to use Microsoft powerbi service but  I am not sure if I have email administration access on my domain account. I will try to reproduce the your exact problem on limesurvey server and o365 account and then try some fixes. If they work out then I will implement them on your server.

Some pointer that I found which may be further helpful.
https://support.office.com/en-us/article/Create-DNS-records-at-any-DNS-hosting-provider-for-Office-365-7B7B075D-79F9-4E37-8A9E-FB60C1D95166?ui=en-US&rs=en-US&ad=US#BKMK_verify

**Comment by gilliankerr** [comment] 2017-05-29 12:38
Thanks for doing this research. I can add SPF records to our DNS settings for logicaloutcomes.net if you tell me what they should say. I'll also check with Sara about the urgency, but it sounds like you're doing great :)

**Comment by saragaudon** [comment] 2017-05-29 14:33
Hi Trivender, thanks for the good work. This issue will need to be figured out, but not as urgent as getting the Orgwise surveys looking good and ready to send. 

My needs are:

Medium, in 5 business days
**DHIS2 Consultant registry surveys**: Sender, responses and issues (everything) to: dhis2@logicaloutcomes.net
-when there is a response, an email notice to 'dhis2@logicaloutcomes.net' is needed.

Less urgent
**Independent Contractor Agreement survey**: responses are sent by email to: sara@logicaloutcomes.net*

*We were testing 'limesurvey@logicaloutcomes.net' as the email, to start with. Once this works, I want to insert my email as the contact.

**Comment by trivender** [comment] 2017-05-29 16:39
Can you please provide me Mx record and spf record for o365 . You can send them to me on skype
![image](https://cloud.githubusercontent.com/assets/1558981/26556947/62695758-44bb-11e7-884d-17991fc06677.png)

**Comment by trivender** [comment] 2017-05-29 16:45
I mean all 3 values here MX,TXT and CNAME

**Comment by gilliankerr** [comment] 2017-05-30 14:56
Trivender, do you have the information you need? I can't tell whether the screenshot I sent you via skype answered this question.

**Comment by trivender** [comment] 2017-05-31 13:20
## Current situation:

- Emails are going to junk folder.
- With current settings as "Send email using remote server" the survey do not submit instantly and there is few seconds wait. Please note that survey got instantly submitted when the setting was "Send email using local server".
- But with current settings as "Send email using remote server" survey submit much quicker than sending mail via SMTP which was taking forever.

**The best solution is to consult with expert webmaster (not network admin) [https://en.wikipedia.org/wiki/Webmaster] . We may reach out core LimeSurvey developers like Denis, Louise to know there opinion.** 

## Other solutions:
Problem: Mails going to junk.(Mails are going to junk only in logicaloutcomes domain. I checked with my gmail and email didn't go in junk)
Solution: Check in office 365 admin panel if there is a way to whitelist inmontion server. Maybe we can reach out o365 support for this.

Problem: Submit is still taking few seconds.
Solution: When user submit survey we can should a progress bar showing a message like "Submitting your response... Please do not close browser.." and a countdown 5,4,3,2,1..".

Other Idea: 
A different approach for emailing: We can use separate application for emailing. Once survey gets submitted we will capture respondent id using query string and then read respondent data using LimeSurvey remote API .. send email.. . As we will not be using LimeSurvey emailing system so no delays in submitting. I have nodejs knowledge and I can prepare a demo.

**Comment by gilliankerr** [comment] 2017-05-31 13:54
Great analysis thanks. Sara and I will talk and decide on next steps

**Comment by trivender** [comment] 2017-05-31 14:12
As pother to white list ip in office 365 https://knowbe4.zendesk.com/hc/en-us/articles/218134997-Whitelisting-by-IP-Address-in-Exchange-2013-2016-or-Office-365

**Comment by saragaudon** [comment] 2017-05-31 14:27
Hi Gillian, want me to contact O365 re: solution 1?

**Comment by gilliankerr** [comment] 2017-05-31 17:23
Sara, I don't know about the security implications of whitelisting inmotion servers. We could use one of our other domains (logicaloutcomes.ca), set it up as an inmotion email server, and use it for limesurvey emails. What do you think?

**Comment by gilliankerr** [comment] 2017-05-31 20:49
@mmirasol Do you have suggestions about how to resolve this issue - outgoing emails?

**Comment by mmirasol** [comment] 2017-05-31 22:17
I would recommend using a 3rd party service like https://www.constantcontact.com/index.jsp to deliver the emails.  Please see my comments on the two issues below.

Problem: Mails going to junk.(Mails are going to junk only in logicaloutcomes domain. I checked with my gmail and email didn't go in junk)
Solution: Check in office 365 admin panel if there is a way to whitelist inmontion server. Maybe we can reach out o365 support for this. 

> different mail hosts have different spam filters so it's best to rely on 3rd party services for this rather than use our own mail server.  the trick behind it is to make sure domains exchange verified info on each email so it does not get flagged as spam.  in addition, you also need to make sure you don't exceed sending limits.  services like constantcontact cover these for you.

Problem: Submit is still taking few seconds.
Solution: When user submit survey we can should a progress bar showing a message like "Submitting your response... Please do not close browser.." and a countdown 5,4,3,2,1..".

> need more info on this. does this only happen with surveys with email notifications on or all of them?

Other Idea:
A different approach for emailing: We can use separate application for emailing. Once survey gets submitted we will capture respondent id using query string and then read respondent data using LimeSurvey remote API .. send email.. . As we will not be using LimeSurvey emailing system so no delays in submitting. I have nodejs knowledge and I can prepare a demo.

> i agree with using an external approach for email. otherwise if the volume is low, we should just use smtp.

**Comment by mmirasol** [comment] 2017-05-31 22:30
Emails are going to junk folder.
> emails would go to junk / spam if domains exchange information which cannot be verified by the receiving server. when emails are sent directly by php, it will easily be flagged as spam.

With current settings as "Send email using remote server" the survey do not submit instantly and there is few seconds wait. Please note that survey got instantly submitted when the setting was "Send email using local server".
> where are these settings? if it's within lime it is to be expected because lime needs to complete the email sending process before it could show the completion page.

But with current settings as "Send email using remote server" survey submit much quicker than sending mail via SMTP which was taking forever.
> lime's email methods are PHP, SMTP, Sendmail and Qmail.
> if the webhosting server has been setup as an email server then PHP would work.
> if Sendmail is setup on the server, Sendmail can be used.
> SMTP will only work if allowed by firewalls but is the most secure way to send the emails out.
@gilliankerr where is this application currently hosted?

**Comment by mmirasol** [comment] 2017-05-31 22:40
@gilliankerr i think this issue is already resolved.
i got an email from sara earlier saying: Hi Mark - the response receive works!
with the email confirmation from lime in the body.

looking at the chat above, Mails are going to junk only in logicaloutcomes domain. and sara got the email so i believe it's good.

i also added myself to the notification and did a test and i received the email in my mirasol.mark@gmail.com inbox.

**Comment by mmirasol** [comment] 2017-05-31 22:40
so unless there are other accounts that can't receive the emails i believe this issue has been resolved.

**Comment by gilliankerr** [comment] 2017-05-31 22:52
It seems like it's working... i will close this now and we can re-open if we find other issues.

**Comment by saragaudon** [comment] 2017-06-01 12:59
@mmirasol see survey admin issue, can you ensure that survey responses are sent by email (not just the admin email is set up) - for the LogicalOutcomes and DHIs2 surveys - I can test again? I wasn't clear from your notes if you had the 'email response when submission received' set up.

**Comment by mmirasol** [comment] 2017-06-01 14:23
yes sara. i received the submission email as admin. and i saw from your forwarded email that you got one from SIS What evaluation services would you like from OCASI?(ID:886367) before too.

as discussed on skype, kindly unflag the email as spam and try again.  the email is flagged as spam because it's not going thru smtp but uses the from address: limesurvey@logicaloutcomes.net

**Comment by mmirasol** [comment] 2017-06-01 14:24
![image](https://cloud.githubusercontent.com/assets/13954274/26684251/00031378-4719-11e7-9d45-68f672d2dd42.png)
![image](https://cloud.githubusercontent.com/assets/13954274/26684260/0ad546ae-4719-11e7-993a-3b08449b75fe.png)
![image](https://cloud.githubusercontent.com/assets/13954274/26684277/13be7fe2-4719-11e7-8186-ab914cad2c02.png)

**Comment by saragaudon** [comment] 2017-06-01 17:02
Given we're exploring this in Issue #18 , closing this. We're getting close!

**Comment by mmirasol** [comment] 2017-06-01 18:07
hi @trivender we just did a smtp test with one of my test emails and the submission emails were sent to the inbox and not to the junk folder of sara@logicaloutcomes.net.  we retested with the smtp settings for limesurvey@logicaloutcomes.net with smtp host smtp.office365.com and it took a long time to submit and we did not get the email so it most likely timed out.

can you please add smtp.office365.com points to 132.245.69.50 to the domain settings of this server.  i believe the domain is currently pointing to its local domain and this is why it's timing out.

**Comment by mmirasol** [comment] 2017-06-01 18:09
@gilliankerr @saragaudon will retest once the setting has been added to the inmotion domain settings.

**Comment by trivender** [comment] 2017-06-02 12:45
I added a A record . Please note it is automatically appending suffix .logicaloutcomes.net.

![image](https://cloud.githubusercontent.com/assets/1558981/26726111/6e9b2504-47bf-11e7-9ce7-0b7697a8a0bc.png)

**Comment by mmirasol** [comment] 2017-06-02 19:54
Thank you. Will test it now.

**Comment by mmirasol** [comment] 2017-06-02 20:18
@trivender please confirm office365.com is not a parked domain on cpanel. could you create an ssh user for me?

**Comment by mmirasol** [comment] 2017-06-02 21:44
@gilliankerr @saragaudon tested the smtp settings for limesurvey@logicaloutcomes.net successfully outside of lime so the troubleshooting that needs to be is on this server.

may i request cpanel access for this?

**Comment by mmirasol** [comment] 2017-06-03 05:20
@gilliankerr @saragaudon was able to successfully send email using limesurvey@logicaloutcomes.net
bad news however is that because of the domain setup and mx records pointing to office365 it takes around 2 mins before the request is processed because it jumps between 2 webhosts (domain server and office 365) on every request.  
![image](https://cloud.githubusercontent.com/assets/13954274/26748189/110a19bc-482e-11e7-8004-f1a9c088a593.png)

In lime, the end process would timeout within 60 s so the email never gets sent out.

recommendation: use an email from another domain with its mx records set locally. 
this has been tested with gmail. i did the same test with my mail account and i was able to send out within 16s.  
![image](https://cloud.githubusercontent.com/assets/13954274/26748195/1ba0bbb0-482e-11e7-9312-b8af0ffdab34.png)

don't worry too much about the 16 s it takes longer because im printing out the smtp debug. 

as long as we send thru smtp, the email won't be flagged as spam as long as the send volume is low.

**Comment by mmirasol** [comment] 2017-06-03 05:21
best would be to park the domain directly on the inmotion server so the email can be sent from the same server as lime but use a domain other than logicaloutcomes.net since you already have this configured in office365.

**Comment by saragaudon** [comment] 2017-06-05 15:29
Hi @mmirasol thank you for continuing with this. Let's not include Gillian in the chat as she does not need this functionality for Orgwise. I need it for SIS and the DHIS2 surveys. Where are we on this task?

**Comment by mmirasol** [comment] 2017-06-05 15:40
Hi @saragaudon gillian made a recommendation.
@saragaudon It looks like we should set up an email server in inmotion with logicaloutcomes.ca or logicaloutcomes.org. Do you agree, and if so, which domain would you prefer?

**Comment by mmirasol** [comment] 2017-06-05 15:40
we might need gillian's help with setting up the domains.

**Comment by saragaudon** [comment] 2017-06-05 15:42
I have access to the accounts, and can try if you tell me exactly what to do!

Sara

---
Sara Gaudon, Executive Director, LogicalOutcomes<http://www.logicaloutcomes.net/>
sara@logicaloutcomes.net<http://www.logicaloutcomes.net/> | Toronto 647-478-5634 x103 Washington 202-779-9634 x103

________________________________

**Comment by mmirasol** [comment] 2017-06-05 15:43
ok we need to add a new domain on inmotion. gillian suggested logicoutcomes.ca or logicaloutcomes.org can you setup one of these on inmotion?

once it's there we can create an email address on inmotion and use that for the smtp setup instead of  limesurvey@logicaloutcomes.net

**Comment by gilliankerr** [comment] 2017-06-07 20:14
Good news! Mark, can you change the username to survey@logicaloutcomes.ca  instead of limesurvey? It's better to simplify it for users. 
@saragaudon you can give Mark the generic email address to forward messages to ....

**Comment by mmirasol** [comment] 2017-06-07 20:38
@gilliankerr @saragaudon emails sent from inmotion are going to spam for logicaloutcomes.ca
before this we tested with gmail smtp settings and it did not go to spam.
this tells us that when inmotion communicates with office365 to deliver the email it cannot prove that our sending address limesurvey@logicaloutcomes.ca is authorized to send email as/from our admin emails.

we need to perform the following steps on inmotion to resolve the spam issue.
1. add txt record for office365 to prove we own the domain.
TXT (Text) @ MS=msXXXXXXXX 1 hour (@gilliankerr need the correct value for this one)
2. add mx record to send to office365.
MX (Mail Exchanger) @ <domain-key>.mail.protection.outlook.com 10 1 hour (@gilliankerr need the correct value for this one)
3. add cnames required by office365.
4. add txt record for spam protection.
ex. TXT (Text) @ v=spf1 include:spf.protection.outlook.com -all 1 hour
ref: https://support.office.com/en-us/article/Create-DNS-records-at-GoDaddy-for-Office-365-f40a9185-b6d5-4a80-bb31-aa3bb0cab48a
5. add srvs required by office365.

**Comment by gilliankerr** [comment] 2017-06-08 13:44
Is this ready to close?

**Comment by saragaudon** [comment] 2017-06-08 15:17
It sure is - thanks @mmirasol for getting this fixed up.

**Closed by saragaudon** 2017-06-08 15:17 UTC
